name: envTesting Workflow
on:
  push:
    branches: [ "main" , "shobhit" ]
  pull_request:
    branches: [ "main" , "shobhit" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Shobhit level'     
        required: true
        default: 'Dev'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run-1
        run: echo Hello, world!
      - name: Run-2
        run: echo ${GITHUB_REF##*/}
  
