name: envTesting Workflow
on:
  push:
    branches: [ "main" , "shobhit" ]
  pull_request:
    branches: [ "main" , "shobhit" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Shobhit level'     
        required: true
        default: 'Dev'
      tags:
        description: 'Test scenario tags'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Job1:
    if: ${{ ${GITHUB_REF##*/} == 'main'}}
#     if: ${{ needs.check-if-there-are-commits.outputs.alive == 'true' }}
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - uses: actions/checkout@v3
      - name: Run-1
        run: echo Hello, world!
      - name: Run-2
        run: echo ${GITHUB_REF##*/}
  
#   Job2:
#     if: ${{GITHUB_REF##*/}} == 'shobhit'
#     runs-on: ubuntu-latest
#     environment: Dev
#     steps:
#       - uses: actions/checkout@v3
#       - name: Run-3
#         run: echo Hello, world!
#       - name: Run-4
#         run: echo ${GITHUB_REF##*/}
